"""
CyborgBench Execution Harness.
Orchestrates multi-axis evaluation runs across Physical AI, BCIs, Reflex Watchdogs,
and Biometric Liveness systems. Emits signed audit dossiers and HTML/Markdown reports.
"""

from dataclasses import dataclass, field, asdict
from typing import Dict, Any, Optional, List
import json

from cyborgbench.core.scoring import CyborgQualityIndex, CQIScore, TierGrade
from cyborgbench.tasks.kinetic_safety import KineticSafetyTask, KineticResult
from cyborgbench.tasks.neural_drift import NeuralDriftTask, NeuralResult
from cyborgbench.tasks.reflex_watchdog import ReflexWatchdogTask, ReflexResult
from cyborgbench.tasks.biometric_liveness import BiometricLivenessTask, BiometricResult
from cyborgbench.compliance.oax_receipt import OAXReceipt, generate_verification_receipt


@dataclass
class BenchmarkConfig:
    system_name: str = "Physical-AI-Autonomous-Agent"
    suite: str = "all"                     # 'all', 'kinetic', 'neural', 'reflex', 'biometric'
    kinetic_steps: int = 1000
    kinetic_jitter_prob: float = 0.15
    neural_drift_angle: float = 25.0
    reflex_stall_ms: float = 50.0
    biometric_genuine_count: int = 100
    biometric_synthetic_count: int = 100
    seed: int = 42


@dataclass
class BenchmarkReport:
    system_name: str
    cqi: CQIScore
    receipt: OAXReceipt
    kinetic: Optional[KineticResult] = None
    neural: Optional[NeuralResult] = None
    reflex: Optional[ReflexResult] = None
    biometric: Optional[BiometricResult] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "system_name": self.system_name,
            "cqi": self.cqi.to_dict(),
            "receipt": self.receipt.to_dict(),
            "kinetic": self.kinetic.to_dict() if self.kinetic else None,
            "neural": self.neural.to_dict() if self.neural else None,
            "reflex": self.reflex.to_dict() if self.reflex else None,
            "biometric": self.biometric.to_dict() if self.biometric else None
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True)

    def to_markdown(self) -> str:
        lines = [
            f"# CyborgBench Leaderboard Dossier: {self.system_name}",
            "",
            f"**Composite Cyborg Quality Index (CQI):** `{self.cqi.cqi:.2f}` / 100.0  ",
            f"**Certification Tier:** **{self.cqi.grade.value}**  ",
            f"**Safety Gated:** `{'YES - CLAMPED' if self.cqi.safety_gated else 'NO - CONFORMANT'}`  ",
            f"**Cryptographic Receipt ID:** `{self.receipt.receipt_id}`  ",
            "",
            "---",
            "",
            "## 1. Multi-Axis Benchmark Breakdown",
            "",
            "| Axis Code | Evaluation Domain | Weight | Score | Status | Key Telemetry |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |"
        ]

        if self.kinetic:
            lines.append(
                f"| `KIP` | Kinetic Invariant Preservation | 35% | `{self.kinetic.score:.2f}` | "
                f"{'PASS' if self.kinetic.passed else 'FAIL'} | "
                f"Breaches: `{self.kinetic.boundary_breaches}`, P99 Latency: `{self.kinetic.p99_cycle_latency_us:.1f}µs` |"
            )
        if self.neural:
            lines.append(
                f"| `SDR` | Substrate Drift Resilience | 25% | `{self.neural.score:.2f}` | "
                f"{'PASS' if self.neural.passed else 'FAIL'} | "
                f"Retention: `{self.neural.retention_ratio * 100:.1f}%`, Drift R²: `{self.neural.drift_r2:.3f}` |"
            )
        if self.reflex:
            lines.append(
                f"| `HRR` | Hardware Reflex Reaction | 20% | `{self.reflex.score:.2f}` | "
                f"{'PASS' if self.reflex.passed else 'FAIL'} | "
                f"Trip Latency: `{self.reflex.trip_latency_us:.1f}µs`, Jerk OK: `{self.reflex.jerk_limit_respected}` |"
            )
        if self.biometric:
            lines.append(
                f"| `BLA` | Biometric Liveness & ZK-Agency | 20% | `{self.biometric.score:.2f}` | "
                f"{'PASS' if self.biometric.passed else 'FAIL'} | "
                f"FAR: `{self.biometric.false_accept_rate * 100:.2f}%`, FRR: `{self.biometric.false_reject_rate * 100:.2f}%` |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 2. Regulatory Standards Mapping",
            ""
        ])
        for std in self.receipt.standards_mapped:
            lines.append(f"- [x] **{std}**")

        lines.extend([
            "",
            "---",
            "",
            f"*Generated by CyborgBench v1.0.0. Cryptographically anchored by A2Z SOC.*"
        ])
        return "\n".join(lines)


class BenchmarkHarness:
    """Main execution engine for running CyborgBench tasks."""

    def __init__(self, config: Optional[BenchmarkConfig] = None):
        self.config = config or BenchmarkConfig()

    def run(
        self,
        kinetic_agent_fn: Optional[Any] = None,
        custom_decoder: Optional[Any] = None,
        watchdog_fn: Optional[Any] = None,
        custom_verifier: Optional[Any] = None
    ) -> BenchmarkReport:
        """Runs the benchmark suite according to the configuration."""
        suite = self.config.suite.lower()

        kinetic_res: Optional[KineticResult] = None
        neural_res: Optional[NeuralResult] = None
        reflex_res: Optional[ReflexResult] = None
        bio_res: Optional[BiometricResult] = None

        # Axis 1: Kinetic
        if suite in ("all", "kinetic"):
            kt = KineticSafetyTask(seed=self.config.seed)
            kinetic_res = kt.run(
                agent_fn=kinetic_agent_fn,
                total_steps=self.config.kinetic_steps,
                jitter_prob=self.config.kinetic_jitter_prob
            )

        # Axis 2: Neural
        if suite in ("all", "neural"):
            nt = NeuralDriftTask(seed=self.config.seed)
            neural_res = nt.run(
                custom_decoder=custom_decoder,
                drift_angle_deg=self.config.neural_drift_angle
            )

        # Axis 3: Reflex
        if suite in ("all", "reflex"):
            rt = ReflexWatchdogTask()
            reflex_res = rt.run(
                watchdog_fn=watchdog_fn,
                simulated_stall_ms=self.config.reflex_stall_ms
            )

        # Axis 4: Biometric
        if suite in ("all", "biometric"):
            bt = BiometricLivenessTask(seed=self.config.seed)
            bio_res = bt.run(
                custom_verifier=custom_verifier,
                num_genuine=self.config.biometric_genuine_count,
                num_synthetic=self.config.biometric_synthetic_count
            )

        # Default neutral scores if single axis run
        kip_s = kinetic_res.score if kinetic_res else 100.0
        sdr_s = neural_res.score if neural_res else 100.0
        hrr_s = reflex_res.score if reflex_res else 100.0
        bla_s = bio_res.score if bio_res else 100.0

        cqi_score = CyborgQualityIndex.evaluate(
            kip=kip_s,
            sdr=sdr_s,
            hrr=hrr_s,
            bla=bla_s,
            details={"suite": suite}
        )

        axis_map = {
            "KIP": kip_s,
            "SDR": sdr_s,
            "HRR": hrr_s,
            "BLA": bla_s
        }

        receipt = generate_verification_receipt(
            target_system=self.config.system_name,
            cqi_score=cqi_score.cqi,
            tier_grade=cqi_score.grade.value,
            axis_scores=axis_map,
            metadata={"suite": suite, "seed": self.config.seed}
        )

        return BenchmarkReport(
            system_name=self.config.system_name,
            cqi=cqi_score,
            receipt=receipt,
            kinetic=kinetic_res,
            neural=neural_res,
            reflex=reflex_res,
            biometric=bio_res
        )
